root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/app ./cmd/api"
  entrypoint = "tmp/app"
  delay = 300
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  exclude_regex = ["_test.go"]

[log]
  time = true

[misc]
  clean_on_exit = true
